# Generated by Django 5.0.1 on 2024-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_backmessage_datasciencemessage_frontmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backmessage',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='datasciencemessage',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='frontmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='backmessage',
            name='image',
            field=models.ImageField(default=1, upload_to='chat_image', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasciencemessage',
            name='image',
            field=models.ImageField(default=1, upload_to='chat_image', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontmessage',
            name='image',
            field=models.ImageField(default=1, upload_to='chat_image', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
