# Generated by Django 5.0.1 on 2024-02-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_backmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default=1, upload_to='chat_image', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
